#!/bin/bash
echo "###################################### WGAN Training is started! 16 Mask-Sets #######################################################"
wandb online
python w_train_per_maskset.py --n_epochs=4000 --batch_size=64 --nchan=512 --ndf=512
echo 
wandb online
echo "###################################### Finish! ############################################"
